ksp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]


urlpatterns += [
    path('inventory/', include('inventories.urls', namespace='inventories')),
    path('services/', include('services.urls', namespace='services')),
    path('sales/', include('sales.urls', namespace='sales')),
    path('', include('inventories.urls',namespace='home')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sales/urls.py
from django.urls import path
from . import views


app_name = 'sales'


urlpatterns = [
    path('create/', views.Create.as_view(), name='create'),
    path('<slug:slug>/update/', views.Update.as_view(), name='update'),
    path('<slug:slug>/delete/', views.Delete.as_view(), name='delete'),
    path('<slug:slug>/', views.Detail.as_view(), name='detail'),
    path('', views.List.as_view(), name='list'),
]

templates/base.html
{% load static %}
{% static 'images/icons/ksp33_16.png' as favicon %}

<!doctype html>
<html lang="en">

<head>
    {% comment %} Required meta tags {% endcomment %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block page_meta %}{% endblock %}

    {# Global styles #}
    {% block site_css %}
    {% include 'css.html' %}
    {% endblock %}

    {# Page-specific styles #}
    {% autoescape off %}
    {% block page_css %}{% endblock %}
    {% endautoescape %}

    {# Extra header stuff (scripts, styles, metadata, etc) #}
    {% block extra_head %} {% endblock %}

    <title>{% block title %} Kopere Stationers & Printers {% endblock title %} | K S & P </title>

    <link rel="shortcut icon" href="{{ favicon }}" type="image/gif" sizes="16x16" />

</head>

<body style="font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;">
    {% include 'navbar.html' %}
    <div class="container-fluid">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'debug' %}light{% else %}{{message.tags}}{% endif %} text-center lead"
            role="alert">
            {{ message.tags }}: {{ message|escape }}
        </div>
        {% endfor %}
        {% endif %}

        {# Page content will go here #}
        {% block body %}
        <h1> No content </h1>
        {% endblock body %}

        {% include 'footer.html' with company_name='Kopere Stationers & Printers' %}

        {# Modal HTML #}
        {% block modals %} {% endblock %}
    </div>


    {# Global javascript #}
    {% block site_js %}
    {% include 'js.html' %}
    {% endblock %}

    {# Shared data for javascript #}
    <script>
    </script>

    {# Page javascript #}
    {% autoescape off %}
    {% block page_js %} {% endblock %}
    {% endautoescape %}
</body>

</html>

templates/css.html
{% load static %}
{% static 'css/bootstrap.css' as bootstrap %}
{% static 'css/main.css' as main %}


<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{{ bootstrap }}" type="text/css" />

<link rel="stylesheet" href="{{ main }}" type="text/css" />

templates/footer.html
{% load static %}

<nav class="navbar navbar-expand-sm navbar-light bg-light">
    <ul class="navbar-nav nav-fill w-100">
        <li class="nav-item active">
            <a class="nav-link m-0 p-0 mr-sm-3 mt-sm-3" href="mailto: info@ksp.co.ke" title="Send Mail to {{ company_name }}">
                <i class="fa fa-envelope-o fa-lg" alt="mail"></i>&nbsp; Mail </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link m-0 p-0 mr-sm-3 mt-sm-3" target="_blank" href="https://www.facebook.com">
                <i class="fa fa-facebook fa-lg" alt="facebook"></i>&nbsp; facebook </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link m-0 p-0 mr-sm-3 mt-sm-3" target="_blank" href="http://www.twitter.com">
                <i class="fa fa-twitter fa-lg" alt="twitter"></i>&nbsp; twitter </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link m-0 p-0 mr-sm-3 mt-sm-3" target="_blank" href="http://www.google.com">
                <i class="fa fa-google-plus fa-lg" alt="google+"></i>&nbsp; Google + </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link m-0 p-0 mr-sm-3 mt-sm-3" target="_blank" href="http://www.linkedin.com">
                <i class="fa fa-linkedin fa-lg" alt="linkedin"></i>&nbsp; LinkedIn </a>
        </li>
    </ul>
</nav>


<div class="row bg-white">
    <div class="col">
        <div class="text-center">
            <span class="lead text-muted">&copy {{ company_name }} {% now "Y" %}</span>
        </div>
    </div>
    <div class="col">
        <div class="text-center">
            <small>This web is designed by <a target="_blank" href="https://www.linkedin.com/in/wangageorge/"> George
                    Wanga </a></small>
            <small>&copy <a target="_blank" href="https://ksp.co.ke"> {{ company_name }} {% now "Y" %} </a></small>
        </div>
    </div>
</div>

templates/js.html
{% load static %}
{% static 'js/jquery-3.5.1.slim.js' as slim %}
{% static 'js/popper.js' as popper %}
{% static 'js/bootstrap.js' as bootstrap %}
{% static 'js/app.js' as app %}


<script src="{{ slim }}"></script>
<script src="{{ popper }}"></script>
<script src="{{ bootstrap }}"></script>

{% comment %} Custom JS {% endcomment %}
<script src="{{ app }}"></script>

templates/navbar.html
{% load static %}
{% url 'inventories:list' as inventories %}
{% url 'services:list' as services %}
{% url 'sales:list' as sales %}

<nav class="navbar navbar-expand-md navbar-light bg-light">
    <a class="navbar-brand mb-0 h1" href="{{ inventories }}">
        <img src="{% static 'images/ksp_100.png' %}" height="30" class="d-inline-block align-top" alt="">
        <strong style="font-family:arial; font-size: x-large;">
            K<span class="text-danger-custom">opere</span>
            S<span class="text-danger-custom">tationers</span> &
            P<span class="text-danger-custom">rinters</span>
        </strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.path == inventories %} active {% endif %}">
                <a class="nav-link" href="{{ inventories }}">
                    Products
                    {% if request.path == inventories %}
                    <span class="sr-only">(current)</span>
                    {% endif %}
                </a>
            </li>
            <li class="nav-item {% if request.path == services %} active {% endif %}">
                <a class="nav-link" href="{{ services }}">
                    Services
                    {% if request.path == services %}
                    <span class="sr-only">(current)</span>
                    {% endif %}
                </a>
            </li>
            <li class="nav-item {% if request.path == sales %} active {% endif %}">
                <a class="nav-link" href="{{ sales }}">
                    Sales
                    {% if request.path == sales %}
                    <span class="sr-only">(current)</span>
                    {% endif %}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/admin"> Admin </a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>