inventories/urls.py
from django.urls import path
from . import views


app_name = 'inventories'


urlpatterns = [
    path('create/', views.Create.as_view(), name='create'),
    path('<slug:slug>/update/', views.Update.as_view(), name='update'),
    path('<slug:slug>/delete/', views.Delete.as_view(), name='delete'),
    path('<slug:slug>/', views.Detail.as_view(), name='detail'),
    path('', views.List.as_view(), name='list'),
]

ksp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]


urlpatterns += [
    path('inventory/', include('inventories.urls', namespace='inventories')),
    path('services/', include('services.urls', namespace='services')),
    path('sales/', include('sales.urls', namespace='sales')),
    path('', include('inventories.urls',namespace='home')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

inventories/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from autoslug import AutoSlugField

import datetime


class Units(models.Model):
    name = models.CharField(
        max_length=32,
    )

    def __str__(self):
        return self.name


class Categories(models.Model):
    name = models.CharField(
        max_length=32,
    )

    def __str__(self):
        return self.name


class Products(models.Model):
    key = models.CharField(
        max_length=8,
    )
    image = models.ImageField(
        blank=True,
    )
    name = models.CharField(
        max_length=32,
    )
    unit = models.ForeignKey(
        Units,
        on_delete=models.DO_NOTHING,
    )
    category = models.ForeignKey(
        Categories,
        on_delete=models.DO_NOTHING,
    )
    q = models.PositiveSmallIntegerField(
        verbose_name=_('Quantity'),
    )
    q_reserve = models.PositiveSmallIntegerField(
        verbose_name=_('Quantity Reserve'),
        help_text=_(
            'Is the minimum quantity of the product that indicates that you must buy more product.'
        ),
    )
    pur_price = models.DecimalField(
        verbose_name=_('Purchase Price'),
        decimal_places=2,
        max_digits=19,
        default=0,
    )
    sal_price = models.DecimalField(
        verbose_name=_('Sale Price'),
        decimal_places=2,
        max_digits=19,
        default=0,
    )
    info = models.TextField(
        verbose_name=_('Additional Product Information.'),
        null=True,
        blank=True,
    )
    pub_date = models.DateTimeField(
        verbose_name=_('Date Added'),
        auto_now=True
    )
    slug = AutoSlugField(populate_from='name', unique_with='pub_date__month')

    def was_added_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def get_absolute_url(self):
        return reverse("inventories:detail", args=[str(self.slug)])

    def __str__(self):
        return self.name

inventories/views.py
from django.utils import timezone
from django.urls import reverse_lazy
from django.views import generic

from .models import Products


class Create(generic.CreateView):
    model = Products
    fields = '__all__'


class List(generic.ListView):

    model = Products
    paginate_by = 100  # if pagination is desired

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class Detail(generic.DetailView):

    model = Products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class Update(generic.UpdateView):
    model = Products
    fields = '__all__'


class Delete(generic.DeleteView):
    model = Products
    success_url = reverse_lazy('inventories:list')

inventories/templates/inventories/base.html
{% extends "base.html" %}
{% load static %}
{% url 'inventories:create' as add_product %}

{% block body %}
<div class=" card p-2 my-4">
    <div class="row">
        <div class="col my-auto">
            <h1>Products</h1>
        </div>
        <div class="col my-auto">
            <a class="btn btn-block btn-outline-primary" href="{% url 'inventories:create' %}">
                <span class="lead"> Add Product </span>
            </a>
        </div>
    </div>
</div>
{% block products_body %}
No Content
{% endblock products_body %}
{% endblock body %}

inventories/templates/inventories/products_confirm_delete.html
{% extends "inventories/base.html" %}

{% block products_body %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock products_body %}

inventories/templates/inventories/products_detail.html
{% extends "inventories/base.html" %}

{% block products_body %}
<h1>{{ object.name }}</h1>
<p>{{ object.category }}</p>
<p>Reporter: {{ object.sal_price }}</p>
<p>Published: {{ object.pub_date|date }}</p>
<p>Date: {{ now|date }}</p>
{% endblock products_body %}

inventories/templates/inventories/products_form.html
{% extends "inventories/base.html" %}

{% block products_body %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock products_body %}

inventories/templates/inventories/products_list.html
{% extends "inventories/base.html" %}
{% load static %}
{% block products_body %}
<div class="card shadow-lg ">
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <caption>
                List of Products
            </caption>
            <thead>
                <tr>
                    <th scope="col">Product Name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Additional information</th>
                </tr>
            </thead>
            <tbody>
                {% for product in object_list %}
                <tr class="shadow-sm">
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <strong class=" text-success-custom ">
                                {{ product.name }}
                            </strong>
                        </a>
                    </td>
                    <td>{{ product.sal_price }}</td>
                    <td>{{ product.info }}</td>
                </tr>
                {% empty %}
                <li>No Products yet.</li>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock products_body %}